### ISSUE TITLE
Imperative tense requirement in docstrings seems weird

### ISSUE THREAD

**Issue by davesque** [ethereum/snake-charmers-tactical-manual#49]
There's a section in the "documentation" article ([here](https://github.com/ethereum/snake-charmers-tactical-manual/blob/93c2d612a3498afd9229f1ff9f83ebbf408f6b78/documentation.md#grammar)) that says the following:

    We use imperative, present tense to describe APIs: “return” not “returns”

    One way to test if we have it right is to complete the following sentence.

    If we call this API it will: __________________________

That construction seems a little awkward to me.  I've tended to use the approach that's discouraged (i.e. "returns" instead of "return") because, IMHO, it reads more naturally.  For example, if function `foo` has a docstring "Returns such and such value.", then it's natural to read, "`foo` returns such and such value."  To me, that's the most simple way to construct a full sentence from the function name and the docstring.

Were there any other reasons we were using that approach other than that it fits into the sentence template described in the article?  If not, I wonder if we would ever consider changing that recommendation to "returns" and not "return".  Or perhaps at least permitting the alternative style that I'm talking about.

**Comment by davesque** [comment]
@cburgdorf Thought I'd ping you on this one since I think you wrote the article originally.

**Comment by cburgdorf** [comment]
I agree with you that it reads more naturally. However, it is pretty common to use imperative present tense among API docs. Here are two very popular examples one of them being Python itself.

Python stdlib

https://docs.python.org/3/library/weakref.html#weakref.getweakrefs

Angular

https://angular.io/api/common/http/JsonpClientBackend#handle

I personally don't care so much as long as it is consistent but we've already done some effort to point out that we are following imperative present tense grammar and correct people in their PRs etc. So I'm hesitant to change it midway. Especially since there is no right or wrong about this. It comes down to taste eventually.

**Comment by davesque** [comment]
@cburgdorf 

I guess I never noticed that the python docs use it.  That's a plus.

Actually, I'll concede that there's another advantage which is that international contributors don't have to do as much work to figure out if a simple present conjugation of a verb is irregular as it would be, for example, with the verb "to go".  The correct conjugation with my approach would be "Goes", but English is weird to maybe let's just be kind and let people use the simple unconjugated verb "Go" to start the docstring. :)

**Comment by davesque** [comment]
@cburgdorf Anyway, between those two advantages, I'll consider the matter settled.  Closing the issue.

**Comment by cburgdorf** [comment]
>Actually, I'll concede that there's another advantage which is that international contributors don't have to do as much work to figure out if a simple present conjugation of a verb is irregular as it would be, for example, with the verb "to go". 

Oh that's a very good point. :+1:  Never thought about that.
